name: build
on: repository_dispatch
jobs:
   build-ubuntu:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: make
         run: make
         working-directory: ./2020/github-actions-protobuf
